exclude: |
  ^README\.md$|
default_language_version:
  python: python3
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
      # - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8 # See .flake8 for args
        additional_dependencies: &flake8-plugins
          - flake8-bugbear
          - flake8-builtins
          # - flake8-broken-line
          - flake8-comprehensions
          - mccabe
          - pep8-naming
          - pycodestyle
          - pyflakes
